image: python:3.6


stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
        - dev
    script:
        - pip install -r chefsApprentice/requirements.txt
        - python chefsApprentice/manage.py makemigrations
        - python chefsApprentice/manage.py migrate
        - python chefsApprentice/manage.py test
        
    
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - pip install docker-compos
        - docker-compose up -d --build
        - pip install -r chefsApprentice/requirements.txt
        - pip install -q -r chefsApprentice/requirements.txt
    environment: master
    when: manual
            