image: python:3.6


stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
        - dev
    script:
        - pip3 install -r chefsApprentice/requirements.txt
        - python3 chefsApprentice/manage.py makemigrations
        - python3 chefsApprentice/manage.py migrate
        - python3 chefsApprentice/manage.py test
        
    
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - pip3 install -r chefsApprentice/requirements.txt
        - pip3 install docker-compose
        - docker-compose build --no-cache
        - docker-compose up -d

    environment: master
    when: manual
            