image: docker

services:
    - docker:dind
    
stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
        - dev
    script:
        - apt install python3-pip
        - pip3 install -q -r requirements.txt
        - python3 manage.py test
        
    
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - apt install python3-pip
        - pip3 install -q -r requirements.txt
        - pip3 install docker-compos
        - docker-compose up -d --build
    environment: master
    when: manual
            