image: docker

services:
    - docker:dind
    
stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
        - dev
    script:
        - apk add python3 python-dev py-pip build-base
        - pip3 install -r chefsApprentice/requirements.txt
        - python manage.py test
        
    
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - apk add python3 python-dev py-pip build-base
        - pip3 install docker-compos
        - pip3 install -r chefsApprentice/requirements.txt
        - docker-compose up -d --build
    environment: master
    when: manual
            