# Generated by Django 2.1.7 on 2019-02-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20190224_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instuction',
            new_name='instruction',
        ),
    ]
