# Generated by Django 2.1.7 on 2019-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20190227_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.png', upload_to='recipe_image'),
        ),
    ]
