# Generated by Django 2.1.5 on 2019-03-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20190226_1309'),
        ('recipe', '0004_auto_20190227_2342'),
    ]

    operations = [
    ]
