# Generated by Django 2.1.5 on 2019-03-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_merge_20190304_0751'),
        ('recipe', '0005_merge_20190304_0652'),
    ]

    operations = [
    ]
