# Generated by Django 2.1.7 on 2019-03-25 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_merge_20190306_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
