# Generated by Django 2.1.7 on 2019-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='info',
            field=models.TextField(),
        ),
    ]
