# Generated by Django 2.1.7 on 2019-03-13 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190313_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_profile',
            new_name='Profile',
        ),
    ]
